### PR TITLE
fixes audit errors and deprecation warnings

### PR DESCRIPTION
**Pull request by retorquere**

### CODE REVIEW

**Comment by cheton** [comment]
The change to the source code is also required.

**Comment by retorquere** [comment]
Which changes? I ran `npm test` and it succeeded.

**Comment by cheton** [comment]
No tests were implemented for this package. It's necessary to switch legacy API from `github` to `@octokit/rest` for the code: https://github.com/cheton/github-release-cli/blob/master/src/index.js#L4

**Comment by retorquere** [comment]
Done

**Comment by cheton** [comment]
Thank you!

**Comment by retorquere** [comment]
My pleasure, but I saw you had to fix a lot of niggles - sorry about those.

**Pull request merged**
